# Site settings
title: Vote Forward
description: The non-partisan Vote Forward project seeks to revitalize American democracy by radically increasing voter turnout.

# Build settings
plugins: ['kramdown']
#theme: jekyll-theme-minimal
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
repository: sjforman/votefwd 
sass:
  style: compressed
